### ISSUE TITLE
Resizing column in grid doesn't work, shows error

### ISSUE THREAD

**Issue by squidjam** [vmware-clarity/core#216]
## Describe the bug

When one clicks on the resizing control (the separator between the data grid columns' headers) an error is shown in the console and nothing else happens:

```        
    Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at s$e.start (4c242522.js:44:31253)
    at host.addEventListener.passive (4c242522.js:44:31213)
```

## How to reproduce
Follow this link to your own documentation and test it out:
https://storybook.core.clarity.design/?path=/docs/internal-stories-grid--column-resize

1.  Go to [your documentation](https://storybook.core.clarity.design/?path=/docs/internal-stories-grid--column-resize)
2.  Click on the resizing handle
3.  See error

## Expected behavior

The column should resize and no error should be displayed in the console

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [x] v6.x

**Framework:**

- [ ] Angular
- [x] React (Where I first experienced it)
- [ ] Vue
- [x] Other: I guess you are using Angular on the core.storybook? not sure

**Framework version:**
React 18 and core's storybook

**Device:**

- Type: laptop computer
- OS: Windows 10
- Browser Edge
- Version 111.0.1661.41 (Official build) (64-bit)

**Comment by kevinbuhmann** [comment]
Thanks for this bug report. I have opened a PR to fix this error.

>Why is there so little documentation around the data grid?

The Clarity Core datagrid is incomplete. It's currently released as a preview.
